persistentVolume:
  capacity: 20Gi
  accessMode: ReadWriteMany
  reclaimPolicy: Retain
  storageClass: efs-sc
  volumeHandle: fs-0a0aab792a7adaf44  # Your EFS File System ID


persistentVolumeClaim:
  namespace: testing  # Change as needed
  accessMode: ReadWriteMany
  storage: 15Gi
  storageClass: efs-sc


testConnection:
  enabled: false

autoscaling:
  enabled: false

deployment:
  enabled: false

service:
  enabled: false

ingress:
  enabled: false

serviceAccount:
  enabled: false


