# Global configurations
#namespace: {{ .Values.global.namespace }}
appName: papertrl-authentication
replicaCount: 2

# Deployment-specific values
deployment:
  image:
    repository: 194978441177.dkr.ecr.us-east-2.amazonaws.com/auth-service
    #tag: {{ .Values.global.tag }}
    #pullPolicy:  {{ .Values.global.pullPolicy }}

#  updateStrategy:
#    type: {{ .Values.global.updateStrategy.type }}
#    rollingUpdate:
#      maxUnavailable: {{ .Values.global.updateStrategy.rollingUpdate.maxUnavailable }}
#      maxSurge: {{ .Values.global.updateStrategy.rollingUpdate.maxSurge }}

  resources:
    requests:
      memory: "1Gi"
      cpu: "200m"
    limits:
      memory: "2Gi"
      cpu: "500m"

  ports:
    containerPort: 6000
    name: http

#  env:
#    configMap:
#      name: {{ .Values.global.env.configMap.name }}
#      keys:
#        db_host: {{ .Values.global.env.configMap.keys.db_host }}
#        db_port: {{ .Values.global.env.configMap.keys.db_port }}
#    secret:
#      name: {{ .Values.global.env.secret.name }}
#      keys:
#        username: {{ .Values.global.env.secret.keys.username }}
#        password:  {{ .Values.global.env.secret.keys.password }}

  readinessProbe:
    tcpSocket:
      port: 6000
    initialDelaySeconds: 120
    periodSeconds: 10

#  volume:
#    claimName:  {{ .Values.global.volume.claimName }}
#    mountPath:  {{ .Values.global.volume.mountPath }}

  affinity:
    architectures:
      - amd64
      - arm64

  nodeSelector:
    nodegroup: backend-node-group

# Service-specific values
service:
  #type: {{ .Values.global.service.type }}
  port:
    name: http
    protocol: TCP
    port: 6000
    targetPort: 6000

# HPA-specific values
hpa:
  minReplicas: 2
  maxReplicas: 5
  cpu:
    targetUtilization: 80
  memory:
    targetUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60

serviceAccount:
  create: false

ingress:
  enabled: false
