apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.appName }}

spec:
  type: {{ .Values.global.service.type }}
  selector:
    app: {{ .Values.appName }}
  ports:
    - name: {{ .Values.service.port.name }}
      protocol: {{ .Values.service.port.protocol }}
      port: {{ .Values.service.port.port }}
      targetPort: {{ .Values.service.port.targetPort }}
