# Global configurations
namespace: testing
appName: papertrl-frontend
replicaCount: 2

# Deployment-specific values
deployment:
  image:
    repository: 194978441177.dkr.ecr.us-east-2.amazonaws.com/papertrl-frontend
    tag: 3.6.6
    pullPolicy:  Always

  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2

  resources:
    requests:
      memory: "1Gi"
      cpu: "200m"
    limits:
      memory: "2Gi"
      cpu: "500m"

  ports:
    containerPort: 80
    name: http

  #  env:
  #    configMap:
  #      name: {{ .Values.global.env.configMap.name }}
  #      keys:
  #        db_host: {{ .Values.global.env.configMap.keys.db_host }}
  #        db_port: {{ .Values.global.env.configMap.keys.db_port }}
  #    secret:
  #      name: {{ .Values.global.env.secret.name }}
  #      keys:
  #        username: {{ .Values.global.env.secret.keys.username }}
  #        password:  {{ .Values.global.env.secret.keys.password }}

  readinessProbe:
    tcpSocket:
      port: 80
    initialDelaySeconds: 120
    periodSeconds: 10

  volume:
    claimName:  efs-pvc
    mountPath:  /papertrl

  affinity:
    architectures:
      - amd64
      - arm64

  nodeSelector:
    nodegroup: frontend_node_group

# Service-specific values
service:

  enabled: true
  name: papertrl-frontend
  type:
  port:
    name: http
    protocol: TCP
    port: 80
    targetPort: 80

# HPA-specific values
hpa:
  minReplicas: 2
  maxReplicas: 5
  cpu:
    targetUtilization: 80
  memory:
    targetUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60

serviceAccount:
  create: false

ingress:
  enabled: true
  className: "alb"
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: "testing-alb"
    alb.ingress.kubernetes.io/target-type: "ip"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'


testConnection:
  enabled: false

notesEnabled: false
