{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "papertrl-frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "papertrl-frontend.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | default "alb" }}
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.name | default "frontend-service" }}
                port:
                  number: {{ .Values.service.port.port | default 80 }}
{{- end }}
